### ISSUE TITLE
dhcp remove alarms, result unclear

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#10]
Hi, would you mind commenting on what the practical effect is of this commit:

https://github.com/arsv/minibase/commit/3f2b8941211cfae75cc54445868d7972624b0072

I haven't understood what the effect will be of the change, how does it affect behaviour of dhcp?

**Comment by arsv** [comment]
`dhcp` used alarm(2) as an extra protection against hang-ups here:
https://github.com/arsv/minibase/blob/17f5ef60f7f58bea2fdda40efa116cc82e64bf75/src/net2/dhcp_wire.c#L347-L353
See select(2) section BUGS, paragraph with O_NONBLOCK (applies to ppoll as well).

Using alarms there wasn't the best idea to begin with, it should be a non-blocking socket instead. Also, it's not even clear whether any protection is needed there, given it's a raw socket.

**Comment by bkauler** [comment]
Ok, closing.
