### ISSUE TITLE
Use MAC address for unique ID

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#11]
This morning I was examining the unique-ID mechanism, and realised that the inability to obtain such for USB devices compromises the usability of the method.

USB devices have vendor-id and product-id, also a serial-number. However, there is no guarantee of uniqueness.

What is needed is for each network device to have a unique ID. Well, they do, the MAC address.

No need to be concerned about the pci path, to assign a unique ID, use the MAC address. It is easy to obtain. It can be done with various utilities, such as:

```
# ip link show wlan0
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether 1c:4d:70:3c:e6:91 brd ff:ff:ff:ff:ff:ff
```

Or, read it directly in /sys:

```
# cat /sys/class/net/wlan0/address
1c:4d:70:3c:e6:91
```

**Comment by arsv** [comment]
Previous version of `ifmon` identified devices by their MACs. It's not a good idea.
MACs can change at any point. Tracking those changes properly is difficult and takes way too much code.

Most likely I will settle on usb-VEND:PROD, maybe suffixed with serial if available.
Using two devices with the same VEND:PROD pair and no serials would be difficult, ifmon won't be able to tell them apart, but it's not a particularly common situation. VEND:PROD ids should be good enough.

**Comment by bkauler** [comment]
My understanding of this is incomplete, but you would be referring to MAC spoofing?

So, I wondered if the original MAC address hardcoded on the network device, could be accessed. Not so, according to these guys:

https://forum.mikrotik.com/viewtopic.php?t=113370

> I think you need to drop your assumption about "virtual" MAC address vs. hard-coded MAC address.
> In practice, they're one and the same because the interface drivers cause the NIC (wireless or ethernet) to use a different MAC address than the one encoded into the ROM of the hardware. At that point, the ROM-based MAC pretty much no longer exists.

Regarding vendor:product IDs, there is also firmware-version, that could increase the chance of the ID being unique. Running "lsusb -v -d vendor:product" (ex lsusb -v -d  0bda:0129) gives "iSerial" which is the serial number, and I think "bcdDevice" is firmware version.

Apparently, the serial number may not be unique. Ditto for firmware-version. But yes, concatenating those three, or four, will give a good probability of a unique ID.

Thanks for the info.

**Comment by bkauler** [comment]
As there is no persistent ID currently being assigned to USB devices, is that why dropping wlan1 profile does not work?

```
# ifctl
2 eth0: lan0
3 eth1: lan1
4 wlan0: wifi0
5 wlan1: wifi1
```

```
# ifctl wlan1 stop
ifctl: ENOENT
```

But, able to drop the profile of eth1:

```
# ifctl eth1 stop
# ifctl
2 eth0: lan0
4 wlan0: wifi0
5 wlan1: wifi1
```

**Comment by bkauler** [comment]
After the above, do this:

```
# ifctl eth1 identify
# echo $?
0
```

...shouldn't that return non-zero result?

**Comment by arsv** [comment]
`ifctl ... identify` should not fail. The meaning of this command is "try to load profile for this device if possible". This is the command that `ifmon` runs for all net devices appearing in the system, just to figure out what they are. Most of the time, it should be expected to not load anything. It should be as quiet as possible.

`ifctl ... id` ("print device id") should fail however if the device is non-identifiable.

`ifctl wlan0 stop` should not report errors, I'll need to check what's wrong there.

**Comment by arsv** [comment]
USB id code added: https://github.com/arsv/minibase/commit/c005e284d33ccf7dfe7722e4a0394fb5b23eb44e
