### ISSUE TITLE
Small problems with ARM machines

### ISSUE THREAD

**Issue by moinejf** [arsv/minitools#14]
Hi,
Your project seems very interesting for small machines, but I fell on some problems. Here are the easier ones to fix.

First, 'cc -dumpmachine' returns "armv7l-linux-gnueabihf", doing ./configure to abort.

Then, I had problems when setting the groups in the /etc/vtmux/tty<n> scripts for X11 and Wayland. The .config of my kernel contains "CONFIG_UID16=y", and this makes the system to have 2 sets 16 and 32 bits for the system calls getgroups, setgroups, getresuid and getresgid. The same problem also exists for i386 machines.

**Comment by arsv** [comment]
armv7l issue fixed.

UID16 issue fixed, thanks for noticing this.
