### ISSUE TITLE
vtmux, X11 and VT switch problem

### ISSUE THREAD

**Issue by moinejf** [arsv/minitools#15]
As vtmux locks the VT switching mechanism, the X server hangs when it wants to switch to the graphic VT. Calling 'unlock' in the /etc/vtmux/tty<n> X11 script resolves this problem.

But a new problem is raised when switching from X11 to a vtmux console and back to X11: the graphic VT is not reachable but with the legacy switch (unlock).

What did I miss?

**Comment by arsv** [comment]
The X server should not be doing the switching, and should not have the permissions to.
While vtmux is running, it should be the only agent doing any switching.

You are probably trying to run an X server not configured for use with vtmux.

https://github.com/arsv/minibase-br/blob/master/brvendor/package/xorg-server-wl/0008-add-support-for-weston-launch-protocol.patch

The logic there is similar to running Xorg with logind, but it uses a different protocol for the communication between Xorg and vtmux. The same protocol Weston uses between the weston process and weston-launch. This is how the tty script should look like:

https://github.com/arsv/minibase-br/blob/master/sys-1-plain/rootfs-dropin/etc/vtmux/tty3

There are bootable images in minibase-br repo with X, Weston and a legacy tty set up side by side, so it can be used as a template.

**Comment by moinejf** [comment]
OK. I did not see the X server patch. Thanks.
