### ISSUE TITLE
vtmux and wayland problem

### ISSUE THREAD

**Issue by moinejf** [arsv/minitools#16]
The DRM video driver of my machine has no GPU driver, so, wayland/weston does not accept the drm-backend (with this strange message: No available targets are compatible with this triple.). So, I use the fbdev-backend.

Starting weston from vtmux works fine, but, the keyboard characters are sent to both weston and the underlaying VT console. Indeed, when the VT cursor reaches the bottom of the screen, a scroll occurs and all the characters of the console are displayed over the wayland screen.

Is there a way to avoid this problem?

**Comment by arsv** [comment]
vtmux controls the DRI switching. fbdev-backend most likely bypasses the DRI, and writes directly into the frame buffer, so it's not affected by DRI.

For vtmux to work in this setup, KMS driver must be available for the video output, and Weston must be running with the DRM backend. Probably with the software backend for Mesa if there's no GPU support, but the output must be through DRM.

I'm not sure how VT switching should be expected to work with fbdev backend, but most likely you'd need a different tool to do it, not vtmux. If switching is not required, disable the VC completely, and just let Weston control inputs and the fbdev exclusively.

**Comment by moinejf** [comment]
I found that it is weston-launch that inhibits the VT keyboard input. Indeed, this does not work with vtmux.
