### ISSUE TITLE
Unclear how dhconf replaces dhcp

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#19]
Alex, hi, I am coming back to look at minibase after some time. Looking at dhconf, I am unclear how it replaces dhcp. Would you mind saying a few words about this?

I was familiar with running "dhcp $IF request", "dhcp $IF cancel", etc., so are these operations no longer required? Is dhconf now something that is totally automatic, nothing to put in any scripts?

**Comment by arsv** [comment]
`dhconf` works like interactive mode `dhcp`, it needs to be spawned when the link becomes usable (carrier up) and stays alive until the link goes down. There's no discontinuous mode anymore

Sample usage:
https://github.com/arsv/minibase/blob/8b723a35f7099418312d0bf2f9a4f069a3214e58/src/wifi/etc/net/wifi-link
https://github.com/arsv/minibase/blob/8b723a35f7099418312d0bf2f9a4f069a3214e58/src/net2/etc/net/config

`stubhcp` is a stub for `dhconf -q`. Note it should be exec'ed to get the signals working.
