### ISSUE TITLE
ifctl cannot be called as expected within /etc/net/identify

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#21]
Trying the scripts that I was using back in jan/feb. This one does not work:

```
#!/bin/sh
#assigns a persistent interface to a script.

echo "+++ identify $1"
IF="$1"

IDflg=""; NET='lan'
[ -d /sys/class/net/${IF}/wireless ] && NET='wifi'

if [ -s /var/local/interfaces ];then
 IDflg="$(ifctl | grep "${IF} mode ${NET}")"
fi

#if not, assign it...
if [ "$IDflg" == "" ];then
 NUM="${IF/*[a-z]/}"
 if [ ! -f /etc/net/mode-${NET}${NUM} ];then
  cp -a /etc/net/mode-${NET} /etc/net/mode-${NET}${NUM}
 fi
 ifctl ${IF} mode ${NET}${NUM}
fi

echo " executing: ifctl $IF identify"
ifctl $IF identify
###end###
```

Whether I should be still doing this is a different question. The question right now, is that running `IDflg="$(ifctl | grep "${IF} mode ${NET}")"` used to return assigned profile, such as "wlan0: mode wifi0". Now, running ifctl within /etc/net/identify only returns "wlan0, running identify"

is this deliberate, that mode information is no longer displayed at this stage?

As the script has nothing in IDflg, it executes `ifctl ${IF} mode ${NET}${NUM}`, and this hangs, does not return. It should not be executed, as the profile has already been assigned, but it should not hang.

From a terminal, I can type `ifctl wlan0 mode wifi0` and it correctly informs me that the profile is already assigned. Is it deliberate that this cannot be run from within the identify script?

**Comment by arsv** [comment]
It is deliberate, for a completely unrelated reason: `ifctl $iface mode foo` waits for `/etc/net/mode-foo $iface` to finish, so it could report success or failure. Script invocations are strictly serialized, at most one script can be running for a given interface at a given time, so `mode-foo $iface` will not get spawned until `identify` exits. So you end up with a deadlock.

I think I should report EBUSY there or something.

PLEASE DON'T DO THAT. You are trying to auto-assign profiles in `identify`, udevd-style. The whole idea of `ifmon` is to avoid that. It will never work right with `ifmon`, it requires a different tool. `identify` should look like this: 

https://github.com/arsv/minibase/blob/8b723a35f7099418312d0bf2f9a4f069a3214e58/src/net2/etc/net/identify

with or without the echo (probably without unless you're trying to debug it). Nothing else should be there. It's up to the user to name profiles and assign them to devices. Just leave `/etc/net/mode-wifi` as is, and let the user run `ifctl wlan0 wifi` interactively. Better yet, drop `mode-wifi` completely, and let `wifi` itself pick the device.
