### ISSUE TITLE
Limitation of ifmon

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#4]
Hi, I think that I have understood the basics of how ifmon, ifctl, etc. work.
It seems that ifmon is somewhat restricted in its capabilities. The man page states:

> Network interfaces in Linux are not static and cannot be reliably configured during system startup. ifmon addresses this problem by monitoring kernel events and spawning scripts to configure interfaces once they appear in the system.

However, I don't think that is the main problem. For most users, the network interfaces are static. What changes is their usability. If the ethernet cable is not plugged in, or the router turned off, the interface is not "live" and unusable.

This "aliveness" is monitored by daemons such as 'networkmamager' and 'ifplugd', and they can automatically respond to a interface becoming alive, or the reverse.

One could also create a polling loop, running 'ethtool' or 'ifplugstatus' to test for aliveness.

In Puppy Linux, for example, there is a startup script that runs 'ifplugstatus' on each of the found ethernet interfaces, if one is found to be live, 'dhcpcd' is run on that interface.

With 'ethtool' you can do something like this:

`ethtool "$INTERFACE" | grep -Fq 'Link detected: yes'`

I don't know if there is any simple way this can be determined by looking in /sys

**Comment by bkauler** [comment]
Oh, yes, there is. Testing eth1. cable plugged in:

```
# cat /sys/class/net/eth1/carrier
1
```
With cable removed:

```
# cat /sys/class/net/eth1/carrier
0
```
Could this detection be incorporated into ifmon?

One little detail about this "aliveness". I do have one router that is somewhat tardy at responding. That is, if a ethernet cable is plugged in, from the PC, the router takes awhile before it responds and makes the cable alive. It was minutes delay.
Testing now, with this router, no delay.

**Comment by arsv** [comment]
It's already there, ifmon spawns conf-request on carrier-up and conf-cancel on carrier-down. It is meant for DHCP only however.

Generic hooks (scripts) for these events were considered, but ultimately rejected. I could not come up with any reasonable use case that wasn't dhcp.

**Comment by bkauler** [comment]
Great, I continue to learn!

Thanks for your thoughtfulness in designing ifmon. I was thinking, as I was typing this issue, that you have probably already considered all of this.

**Comment by bkauler** [comment]
Closing this issue.
