### ISSUE TITLE
Most appropriate way to run and kill net daemons

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#6]
My traditional thinking, to start and stop 'ifmon' and 'wsupp', might be something like /etc/init.d/minibase-net:

```
#!/bin/sh
case "$1" in
 start)
  mkdir -p /run/ctrl
  #note, the full start-stop-daemon from dpkg is required (not busybox applet)...
  #-S start, -b background, -C do not close fd, -x execute
  start-stop-daemon -S -b -C -x /sbin/ifmon >> /var/log/ifmon.log 2>&1
  start-stop-daemon -S -b -C -x /sbin/wsupp >> /var/log/wsupp.log 2>&1
 ;;
 stop)
  #-K kill
  start-stop-daemon -K -x /sbin/wsupp
  start-stop-daemon -K -x /sbin/ifmon
 ;;
esac
```

However, as 'ifmon' and 'wsupp' do recognise if already running, that is one less reason to use 'start-stop-daemon'. They don't background themselves, but that could be achieved by appending "&", so perhaps this would suffice:

```
#!/bin/sh
case "$1" in
 start)
  mkdir -p /run/ctrl
  ifmon >> /var/log/ifmon.log 2>&1 &
  wsupp >> /var/log/wsupp.log 2>&1 &
 ;;
 stop)
 killall ifmon
 killall wsupp
;;
esac
```

Do you have any thoughts about the correct way to do this? Also, for a generic shutdown, would it be appropriate to do anything else before killing ifmon and wsupp? -- I do understand that perhaps bringing down the "up" interfaces would be appropriate.

I also realise that I am taking these utilities out of context. They are intended to work in minibase, with its own process manager.

**Comment by arsv** [comment]
Either way would work.

There's nothing specific about `svhub` that they depend on by the way, any `runit`-like supervisor would work exactly the same way. If you're running sysvinit or busybox init, you can try something like

    ws:3:respawn:/sbin/wsupp
    if:3:respawn:/sbin/ifmon

in /etc/inittab, although it's probably not worth doing permanently. 
Busybox may require the first field to be empty.
