### ISSUE TITLE
wsupp waits forever for AP

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#7]
I have now got onto exploring wifi. Yes, works, but...

```
# wifi
AP -49   6b  2CC  HUAWEINova2
AP -59  13b  2CC  Telstra7A2DCB

Device wlan1 idle
# wifi scan
AP -51   6b  2CC  HUAWEINova2
AP -63  13b  2CC  Telstra7A2DCB
# wifi connect HUAWEINova2
Passphrase: XXXXXXXXXX
wifi: connected to AP HUAWEINova2 (6b/2437MHz)

# wifi detach
# wifi
wifi: service inactive
# wifi device wlan1
# wifi
AP -55   6b  2CC  HUAWEINova2
AP -63  13b  2CC  Telstra7A2DCB

Device wlan1 idle
# 
```

Yes, it works. As you can see above, I ran "wifi detach". If I now wait about 15 minutes and try again:

```
# wifi scan
AP -53   6b  2CC  HUAWEINova2
AP -65  13b  2CC  Telstra7A2DCB
# wifi connect HUAWEINova2
```

...hung. in another terminal:

```
# wifi
AP -53   6b  2CC  HUAWEINova2
AP -65  13b  2CC  Telstra7A2DCB

Waiting for AP HUAWEINova2 (6b/2437MHz)
# 
```
wsupp is now unresponsive, cannot detach, even killing it and restarting, still cannot obtain the AP.

What is happening here is something to do with my phone. I am using it as a hotspot, and an AP can only be obtained very soon after the hotspot is activated on the phone. After so many minutes (don't know exactly how long, but I waited for 15 minutes above), the AP can no longer be obtained.

wpa_supplicant has the same problem, which is one reason why I am investigating alternatives. Yet, Windows 10 has absolutely no problem with getting the AP. 

Someone suggested that the phone might go into some kind of low-power mode sometime after the hotspot is brought up. However, Win10 has no problem with obtaining the AP, no matter how long the phone has been sitting there without any clients connected to the hotspot.

So, what does Win10 do to "wake up" the phone? Or whatever.

One other thing, with wpa_supplicant, if I turn off the hotspot on the phone then back on, wpa_supplicant then succeeds. But not wsupp, it is stuck waiting forever.

Any thoughts?

**Comment by bkauler** [comment]
Oh, another point: There is a battery-saving mode in Android, that is turned off, and the mains adaptor is plugged in.

**Comment by arsv** [comment]
If it happens with wpa_supplicant as well, try running `wpa_supplicant -dd ...` to check what exactly goes on there. Maybe post the log somewhere. Just make sure to mask sensitive information there — it will contain, at least, BSSIDs (MACs) and SSIDs (names) of your AP and any other APs around you. What kind of client device you've got may be important as well.

It doesn't sound good however. I would guess the card takes a command but fails to generate completion event for that command. The card is effectively a black box if that's what happens.

I'll need to do something about wsupp's inability to detach from a stuck card, but it won't be any more effective than a simple restart.

By the way, can you scan a card that seems stuck?

**Comment by bkauler** [comment]
Well, not a card, it is my Android phone that is tethered, that is, the wifi hotspot. On my PC, currently using a USB wifi dongle, but the same situation happens whatever hardware is at the PC end (I have several PCs and laptops to test with).

Yes, "wifi scan" still works, and sees my phone SSID, even though wsupp is stuck waiting for an AP.

Yes, wsupp should at least timeout. 

When I was testing wpa_supplicant, I did do some detailed logging. Can't recall exactly, but it was in a loop, timing out, then trying again, and I think it eventually gave up and terminated.

It really does annoy me that Win10 has no problem!

**Comment by arsv** [comment]
Retries likely indicate authentication error. EAPOL lacks error reporting, the AP just drops any packets it doesn't like. However, both `wsupp` and `wpa_supplicant` should be able to report that. Might be something else going on.

**Comment by rofl0r** [comment]
if you have a second wifi adapter you could put that one into monitor mode and sniff the packets flying through the air with wireshark. then compare the difference between what happens with windows 10 and wsupp/wpa_supp. the pcap recordings from wireshark could eventually give some clues.

**Comment by bkauler** [comment]
'wifi' hanging is causing me some trouble. I setup another AP to experiment with:

```
# wifi
AP -29   4b  2CC  TP-LINK_7F56
AP -49  11b  2CC  HUAWEINova2
AP -61   6b  2CC  Telstra7A2DCB
AP -73   9b  2CC  BuckRogers

Device wlan1 idle
# wifi connect TP-LINK_7F56
Passphrase: XXXXXXX
wifi: cannot connect to AP TP-LINK_7F56 (4b/2427MHz)
```

...hangs. In another terminal:

```
# wifi
AP -33   4b  2CC  TP-LINK_7F56
AP -49  11b  2CC  HUAWEINova2
AP -61   6b  2CC  Telstra7A2DCB
AP -73   9b  2CC  BuckRogers

Device wlan1 idle
```

TP-LINK_7F56 works, I am using it right now, using wpa_supplicant. But, apart from 'wifi' reporting "cannot connect", hanging forever should not happen, it should terminate.

**Comment by arsv** [comment]
Ok, I think I figured it out. It was a bug and it did not report no-connect at all.
Fixed, `wifi` should terminate properly now.

Also, disconnects are now timed, so wsupp should not get stuck in disconnecting state anymore. It does not guarantee the card will remain usable, but at least it should be possible now to command another connect attempt without restarting wsupp.

Please delete wifi-psk and let `wifi` re-create it, there's a minor format change there.

**Comment by bkauler** [comment]
I have tested, working great. Getting connections to the TP-Link AP, no failures.
