### ISSUE TITLE
ifmon carrier up/down detection insufficient

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#8]
Ha ha, another issue for you!

Yes, ifmon detects if a ethernet cable is plugged in and unplugged, however, it does not detect if the router is turned on or off.
In other words, if the cable is plugged in and router turned off, so no network connection. Then turn on router, now the router has Internet connection, cable is alive, but ifmon does not respond. ifmon does not detect this new situation and does not bring up the network.

'nicmon.c' is a little program that does successfully detect both occurrences, cable plug/unplug and router on/off. Testing, starting with router turn on, cable plugged in:

`# ./nicmon2`

Turn off router:

`Event recieved >> NETLINK::Down`

Turn on router:

```
Event recieved >> Event recieved >> NETLINK::Up
Event recieved >> NETLINK::Down
Event recieved >> NETLINK::Up
Event recieved >> NETLINK::Down
Event recieved >> NETLINK::Up
```

...above happens in quick succession. ifmon has not detected anything, so has not brought up the Internet.

Unplug cable:

`Event recieved >> NETLINK::Down`

Plug in cable:

`Event recieved >> NETLINK::Up`

...and ifmon responds and brings up the Internet.

I did not write nicmon.c, found it somewhere on Internet. Notice that the author may have tried just "addr.nl_groups = RTMGRP_LINK;", then changed it to "addr.nl_groups = RTMGRP_LINK | RTMGRP_IPV4_IFADDR | RTMGRP_IPV6_IFADDR;".

Anyway, here is the code for nicmon.c, in case you find it useful:

```
#include <asm/types.h>
#include <sys/socket.h>
#include <unistd.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <net/if.h>
#include <netinet/in.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <stdlib.h>
#include <sys/time.h>
#include <sys/types.h>

int
read_event (int sockint)
{
  int status;
  int ret = 0;
  char buf[4096];
  struct iovec iov = { buf, sizeof buf };
  struct sockaddr_nl snl;
  struct msghdr msg = { (void *) &snl, sizeof snl, &iov, 1, NULL, 0, 0 };
  struct nlmsghdr *h;
  struct ifinfomsg *ifi;

  status = recvmsg (sockint, &msg, 0);

  if (status < 0)
  {
      /* Socket non-blocking so bail out once we have read everything */
      if (errno == EWOULDBLOCK || errno == EAGAIN)
      return ret;

      /* Anything else is an error */
      printf ("read_netlink: Error recvmsg: %d\n", status);
      perror ("read_netlink: Error: ");
      return status;
  }

  if (status == 0)
   {
      printf ("read_netlink: EOF\n");
   }

  // We need to handle more than one message per 'recvmsg'
  for (h = (struct nlmsghdr *) buf; NLMSG_OK (h, (unsigned int) status);
       h = NLMSG_NEXT (h, status))
    {
      //Finish reading 
      if (h->nlmsg_type == NLMSG_DONE)
        return ret;

      // Message is some kind of error 
      if (h->nlmsg_type == NLMSG_ERROR)
    {
          printf ("read_netlink: Message is an error - decode TBD\n");
          return -1;        // Error
        }

      if (h->nlmsg_type == RTM_NEWLINK)
        {
        ifi = NLMSG_DATA (h);
            printf ("NETLINK::%s\n", (ifi->ifi_flags & IFF_RUNNING) ? "Up" : "Down");
    }
    }

  return ret;
}

int
main (int argc, char *argv[])
{
  fd_set rfds, wfds;
  //struct timeval tv;
  int retval;
  struct sockaddr_nl addr;

  int nl_socket = socket (AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
  if (nl_socket < 0)
    {
      printf ("Socket Open Error!");
      exit (1);
    }

  memset ((void *) &addr, 0, sizeof (addr));

  addr.nl_family = AF_NETLINK;
  addr.nl_pid = getpid ();
  addr.nl_groups = RTMGRP_LINK | RTMGRP_IPV4_IFADDR | RTMGRP_IPV6_IFADDR;
//  addr.nl_groups = RTMGRP_LINK;

  if (bind (nl_socket, (struct sockaddr *) &addr, sizeof (addr)) < 0)
    {
      printf ("Socket bind failed!");
      exit (1);
    }

  while (1)
    {
      FD_ZERO (&rfds);
      FD_CLR (nl_socket, &rfds);
      FD_SET (nl_socket, &rfds);

      //tv.tv_sec = 10;
      //tv.tv_usec = 0;

      //retval = select (FD_SETSIZE, &rfds, NULL, NULL, &tv);
      retval = select (FD_SETSIZE, &rfds, NULL, NULL, NULL); //wait forever.
      if (retval == -1)
        printf ("Error select() \n");
      else if (retval)
        {
          printf ("Event recieved >> ");
          read_event (nl_socket);
        }
      else //0=timed-out, should not happen.
        printf ("## Select TimedOut ## \n");
    }
  return 0;
}
```

**Comment by arsv** [comment]
Could you try running it with this patch?
https://gist.github.com/arsv/ba776748c44e5763af2ff9b93fe70b6f

> ifi->ifi_flags & IFF_RUNNING) ? "Up" : "Down"

That's exactly what ifmon monitors:

https://github.com/arsv/minibase/blob/ebf7f023b3e6edf242d871f4b0e62c21a5eeb572/src/net2/ifmon_netlink.c#L82

Also afaik there's no such thing as cable detection, at least at userspace level. It only detects carrier. The cable is unplugged, or cable is plugged but the router is off — it's the same state, "no-carrier".

The problem is not that it cannot detect router-off condition, it can. Rapid changes in carrier state are most likely the problem.

**Comment by bkauler** [comment]
The situation in the first post, with cable plugged in and router turned off. 'ifmon' with the traces patch is running. Now turn on the router:

```
carrier up on eth0
carrier rising edge
fork 5365 conf-request eth0
+++ conf-request eth0
dhcp: discover: ETIMEDOUT
exit 5365 65280
carrier down on eth0
carrier falling edge
carrier up on eth0
carrier rising edge
fork 5427 conf-request eth0
+++ conf-request eth0
dhcp: discover: ETIMEDOUT
exit 5427 65280
```

...interesting, is is calling conf-request. Now, unplug the cable:

```
carrier down on eth0
carrier falling edge
```

Now plug in the cable:

```
carrier up on eth0
carrier rising edge
fork 6286 conf-request eth0
+++ conf-request eth0
+++ dhcp-gw 192.168.1.1
+++ dhcp-dns 192.168.43.1 168.126.63.2
exit 6286 0
assuming discontinuous mode dhcp
```

...and now online!

**Comment by arsv** [comment]
Ah, I see. The router brings up carrier early but cannot respond to DHCP requests until much later in its boot process. The initial configuration attempt times out before the router boots up, and ifmon never re-tries.

So my current idea on this is to increase re-send timeout and the number of allowed re-sends for `dhcp`, let it try for several seconds maybe, and also probably add a command to `ifctl` to force a re-try. Neither is a good solution, but I don't think there's any way for `ifmon` to know that the router is finally ready.

This may be a valid reason to introduce per-profile dhcp scripts, at least as an option.

**Comment by bkauler** [comment]
Yes, it will need a fix, even if not optimal, as I think this is probably a common situation, the user forgetting to turn on the modem/router, or having to reset it.

**Comment by bkauler** [comment]
I have a workaround, not elegant, but it works. In /etc/net/conf-request, I inserted a call to script /sbin/dhcp-delayed:

```
#!/bin/sh
IF="$1"
echo "+++ conf-request ${IF}"
dhcp-delayed ${IF} & #fallback
dhcp ${IF} request
```

Content of /sbin/dhcp-delayed:

```
#!/bin/sh
IF="$1"
PIDS=$(pidof dhcp-delayed | wc -w) #get 2 when only one running.
[ $PIDS -gt 2 ] && exit
sleep 40
DNS="$(dhcp ${IF} show | grep '^dns ')"
[ "$DNS" ] && exit
echo "Attempting delayed execution: dhcp ${IF} request"
dhcp $IF request
```
Pretty simple, dhcp-delayed waits long enough so that all the carrier up/downs have finished, and if the "dhcp $IF request" has not succeeded, does it again.

I don't know if anything like this can be put into ifmon, but anyway, the script works for me. 40 seconds is just long enough, might be better to increase it a bit.

**Comment by arsv** [comment]
Currently `dhcp` keeps re-trying for 5s. Which is about as high as it should be for this mode of operation. I thought it was lower but turns out I changed the timeout some time ago. Timeouts around 40s call for a different solution.  A script like this is very host-specific, I cannot just hard-code some large time constant and expect it to work well for everyone.

I checked a couple of other implementations, `dhcpcd` retries for 30s by default and `udhcpd` from Busybox for 20s. That's already high enough to be configurable (prompting per-profile scripts) yet probably too low to handle your case.

Not sure what's the proper solution here. `dhcp` is designed around the assumption that it can be a short-running tool. And that should be enough for the vast majority of cases, per my understanding of the DHCP protocol. DHCP makes no provisions for servers suddenly appearing long after the clients sent all their requests.

Your script is actually a good idea, but it can be simplified further.
conf-request:

    #!/bin/sh
    dhcp-delayed $1

dhcp-delayed:

    #!/bin/sh
    dhcp $1 request && exit 0
    sleep 40
    dhcp $1 request

Your own custom double-request dhcp client.
