### ISSUE TITLE
wsupp cannot run wifi-wpa

### ISSUE THREAD

**Issue by bkauler** [arsv/minitools#9]
wsupp logs this:

`wsupp: exec /etc/net/wifi-wpa: ENOENT`

"ENOENT" means "no such file or directory", however, it does exist, and is executable.

Why is this happening?

**Comment by arsv** [comment]
Check #! interpreter within the script.

If the interpreter is ok, try `strace -o ... -f wsupp` to see what exactly it is trying to do.

**Comment by bkauler** [comment]
So sorry to have bothered you! I am dumb, didn't check:

https://github.com/arsv/minibase/blob/master/src/wifi/etc/net/wifi-wpa

I was using the script downloaded Feb. 2nd, with this shebang line:

`#!/sbin/msh`

Sorry, will close this issue...
